=== VitSimon/Utils-XMLDocReader/validation.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="content">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="itemD" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="treelink" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="typestring">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="typefilepath">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="title" type="typestring" />
	<!--<xs:element name="txt" type="typestring" />-->
	<xs:element name="txt">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:any processContents="lax" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="treeicon" type="typefilepath" />
	<xs:element name="filepath" type="typefilepath" />
	<xs:element name="embedfile" type="typefilepath" />
	<xs:element name="itemD">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="title" minOccurs="1" maxOccurs="1" />
					<xs:element ref="txt" minOccurs="0" maxOccurs="1" />
					<xs:element ref="treeicon" minOccurs="0" maxOccurs="1" />
					<xs:element ref="filepath" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="embedfile" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="itemD" minOccurs="0" maxOccurs="unbounded" />
					<xs:element ref="treelink" minOccurs="0" maxOccurs="unbounded" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="treelink">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="title" minOccurs="1" maxOccurs="1" />
					<xs:element ref="filepath" minOccurs="1" maxOccurs="1" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== VitSimon/Utils-XMLDocReader/xmlFileTest2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xmlFileTestTransf.xsl"?>
<content
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="validation.xsd"
>
	<itemD>
		<title>Test second</title>
		<txt>text 1
			<b>be</b>
			<p>Lorem ipsum dolor sit amet &lt;br&gt; Consectetuer ac iaculis diam velit &lt;br&gt;</p>Morbi leo Aenean orci lorem &lt;br&gt; Justo fringilla ante facilisis mauris &lt;br&gt; Nulla Pellentesque montes orci semper &lt;br&gt; Vestibulum venenatis Aenean mi pellentesque &lt;br&gt; Semper id risus elit id &lt;br&gt; Dictum vel nibh In dignissim &lt;br&gt; Sed pretium habitasse vitae hendrerit &lt;br&gt; Nam Quisque ut ut Duis &lt;br&gt; Ac netus elit laoreet Nullam &lt;br&gt; Id ut Nullam wisi interdum &lt;br&gt; Lacus Sed est Curabitur ac &lt;br&gt; Vestibulum sapien cursus nec Sed &lt;br&gt;</txt>
		<embedfile>Include2.html</embedfile>
	</itemD>
	<itemD>
		<title>See also</title>
		<treelink>
			<title>Back to main document</title>
			<filepath>xmlFileTest.xml</filepath>
		</treelink>
	</itemD>
</content>
